# Generated by Django 4.1.13 on 2024-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_nt', '0002_alter_signals_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signals',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
