# Generated by Django 4.1.13 on 2024-08-19 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_nt', '0003_alter_signals_message_alter_signals_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 15, 16, 27, 589070, tzinfo=datetime.timezone.utc)),
        ),
    ]
